server:
  port: 8011
spring:
  application:
    name: admin-client # 给client应用取个名字
  boot:
    admin:
      client:
        url: "http://localhost:8010" #定义client注册服务到8010端口
info: # 自定义属性及信息
  code: A100
  body: demo
management:
  endpoints:
    web:
      exposure:
        include: "*"  #开放所有的接口监听
